# -*- coding: utf-8 -*-
"""RL_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O9VNYL2YB8rf6QngpA_YRfwOrhSPp-jM

#Reinforcement Learning

## Problem setup
"""

!pip install "stable-baselines3>=2.9.0" gymnasium yfinance scipy -q

import os, time, pickle
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import gymnasium as gym
from gymnasium import spaces
from collections import deque
from scipy.optimize import minimize
import yfinance as yf
from stable_baselines3 import PPO, A2C, SAC, TD3
from stable_baselines3.common.monitor import Monitor
from stable_baselines3.common.env_checker import check_env
ALGO_MAP = {'PPO': PPO, 'A2C': A2C, 'SAC': SAC, 'TD3': TD3}

from google.colab import drive
drive.mount('/content/drive')
ROOT = '/content/drive/MyDrive/rl_portfolio'
RES_DIR, MODEL_DIR = f'{ROOT}/results', f'{ROOT}/models'
LOG_DIR, TB_DIR = f'{ROOT}/logs', f'{ROOT}/tb'
for d in (ROOT, RES_DIR, MODEL_DIR, LOG_DIR, TB_DIR):
    os.makedirs(d, exist_ok=True)
RES_CSV, DATA_PKL = f'{RES_DIR}/results.csv', f'{ROOT}/data.pkl'

TICKERS = ['AAPL', 'MSFT', 'NVDA', 'AMZN', 'GLD', 'USO', 'SPY']
START, END = '2015-01-01', '2024-12-31'
SPLIT = '2022-01-01'
VOL_WINDOW = 20
FEATURE_MODE = 'compact'

"""Download adjusted prices, build the feature series, and standardize returns and volatility with a **causal trailing-window z-score** (uses only past data, so no leakage).

"""

def causal_zscore(df, window=252, min_periods=20):
    m = df.rolling(window, min_periods=min_periods).mean()
    s = df.rolling(window, min_periods=min_periods).std()
    return ((df - m) / (s + 1e-8)).fillna(0.0)

def get_data(tickers, start, end, vol_window, split, z_window=252):
    px = yf.download(tickers, start=start, end=end, auto_adjust=True,
                     progress=False)['Close'][tickers].dropna()
    simple = px.pct_change()
    logr = np.log(px / px.shift(1))
    vol = logr.rolling(vol_window).std()
    r5 = np.log(px / px.shift(5))
    r21 = np.log(px / px.shift(21))
    z_logret, z_vol = causal_zscore(logr, z_window), causal_zscore(vol, z_window)
    zc = {k: causal_zscore(v, z_window)
          for k, v in {'r1': logr, 'r5': r5, 'r21': r21, 'v21': vol}.items()}
    keep = vol.dropna().index.intersection(r21.dropna().index)
    sl = lambda d: d.loc[keep]
    px, simple, logr, vol = sl(px), sl(simple), sl(logr), sl(vol)
    z_logret, z_vol = sl(z_logret), sl(z_vol)
    compact = np.concatenate([sl(zc['r1']).values, sl(zc['r5']).values,
                              sl(zc['r21']).values, sl(zc['v21']).values], axis=1)
    train = px.index < pd.Timestamp(split)
    return {'tickers': list(px.columns), 'dates': px.index, 'prices': px.values,
            'simple_ret': simple.values, 'log_ret': logr.values, 'vol': vol.values,
            'z_logret': z_logret.values, 'z_vol': z_vol.values, 'compact': compact,
            'train_mask': train, 'test_mask': ~train, 'vol_window': vol_window}

REQUIRED = {'z_logret', 'z_vol', 'compact', 'prices', 'simple_ret',
            'train_mask', 'test_mask', 'dates', 'tickers'}
data = None
if os.path.exists(DATA_PKL):
    cached = pickle.load(open(DATA_PKL, 'rb'))
    if REQUIRED.issubset(cached.keys()):
        data = cached
    else:
        print('Cached data is from an older version - rebuilding.')
if data is None:
    data = get_data(TICKERS, START, END, VOL_WINDOW, SPLIT)
    pickle.dump(data, open(DATA_PKL, 'wb'))
print(len(data['dates']), 'trading days |',
      int(data['train_mask'].sum()), 'train |', int(data['test_mask'].sum()), 'test')
print(data['dates'][0].date(), '->', data['dates'][-1].date())

"""**Step 1 — the data.** Normalized price paths with the train/test cut, and the return-correlation structure (diversification across tech, gold, oil, the index)."""

px = pd.DataFrame(data['prices'], index=data['dates'], columns=data['tickers'])
ret = pd.DataFrame(data['simple_ret'], index=data['dates'], columns=data['tickers'])
fig, ax = plt.subplots(1, 2, figsize=(15, 4.5))
(px / px.iloc[0]).plot(ax=ax[0], lw=1)
ax[0].axvline(pd.Timestamp(SPLIT), color='k', ls='--', alpha=.6)
ax[0].set_title('Normalized prices (train | test)'); ax[0].set_ylabel('growth of $1')
im = ax[1].imshow(ret.corr(), vmin=-1, vmax=1, cmap='coolwarm')
ax[1].set_xticks(range(7)); ax[1].set_xticklabels(data['tickers'], rotation=45)
ax[1].set_yticks(range(7)); ax[1].set_yticklabels(data['tickers'])
ax[1].set_title('Daily-return correlation'); fig.colorbar(im, ax=ax[1], fraction=.046)
plt.tight_layout(); plt.show()

fig, ax = plt.subplots(1, 2, figsize=(15, 4.5))
ann_ret = ret.mean() * 252
ann_vol = ret.std() * np.sqrt(252)
ax[0].scatter(ann_vol, ann_ret)
for t in data['tickers']:
    ax[0].annotate(t, (ann_vol[t], ann_ret[t]))
ax[0].set_xlabel('annualized volatility'); ax[0].set_ylabel('annualized return')
ax[0].set_title('Risk / return by asset'); ax[0].grid(alpha=.3)
(ret.rolling(63).std() * np.sqrt(252)).plot(ax=ax[1], lw=1)
ax[1].set_title('Rolling annualized volatility (63d)'); ax[1].set_ylabel('volatility')
plt.tight_layout(); plt.show()

"""### Environment

"""

def softmax(x):
    x = x - x.max()
    e = np.exp(x)
    return e / e.sum()

class PortfolioEnv(gym.Env):
    def __init__(self, data, lookback=30, lam=0.5, tc=0.001, rf=0.0,
                 feature_mode='compact', start=None, end=None):
        super().__init__()
        self.prices, self.simple_ret = data['prices'], data['simple_ret']
        self.z_logret, self.z_vol = data['z_logret'], data['z_vol']
        self.compact = data['compact']
        self.N = self.prices.shape[1]
        self.lookback, self.lam, self.tc, self.rf = lookback, lam, tc, rf
        self.feature_mode = feature_mode
        self.vol_window = data.get('vol_window', 20)

        n = len(self.prices)
        self.start = lookback if start is None else max(int(start), lookback)
        self.end = n - 1 if end is None else int(end)

        obs_dim = (self.compact.shape[1] if feature_mode == 'compact'
                   else 3 * self.N * lookback) + (self.N + 1)
        self.observation_space = spaces.Box(-np.inf, np.inf, (obs_dim,), np.float32)
        self.action_space = spaces.Box(-1.0, 1.0, (self.N + 1,), np.float32)
    def reset(self, seed=None, options=None):
        super().reset(seed=seed)
        self.t = self.start
        self.w = np.zeros(self.N + 1); self.w[-1] = 1.0
        self.value = 1.0
        self.hist = deque(maxlen=self.vol_window)
        return self._obs(), {}
    def _obs(self):
        if self.feature_mode == 'compact':
            feat = self.compact[self.t]
        else:
            lo, hi = self.t - self.lookback + 1, self.t + 1
            p = self.prices[lo:hi]; p = p / p[0]
            feat = np.concatenate([p.ravel(), self.z_logret[lo:hi].ravel(),
                                   self.z_vol[lo:hi].ravel()])
        return np.concatenate([feat, self.w]).astype(np.float32)
    def step(self, action):
        w = softmax(np.asarray(action, dtype=float).ravel())
        risky, risky_prev = w[:self.N], self.w[:self.N]
        cost = self.tc * np.abs(risky - risky_prev).sum()
        port_ret = float(risky @ self.simple_ret[self.t + 1] + w[self.N] * self.rf)
        self.value *= 1 + port_ret - cost
        self.hist.append(port_ret)
        pvol = float(np.std(self.hist)) if len(self.hist) > 1 else 0.0
        reward = port_ret - self.lam * pvol - cost
        self.w, self.t = w, self.t + 1
        done = bool(self.t >= self.end)
        return self._obs(), reward, False, done, {
            'value': self.value, 'ret': port_ret, 'cost': cost, 'weights': self.w.copy()}

def make_envs(data, lookback, lam, feature_mode='compact', tc=0.001):
    tr, te = np.where(data['train_mask'])[0], np.where(data['test_mask'])[0]
    common = dict(data=data, lookback=lookback, lam=lam, tc=tc, feature_mode=feature_mode)
    train = PortfolioEnv(start=max(lookback, int(tr[0])), end=int(tr[-1]), **common)
    test = PortfolioEnv(start=max(lookback, int(te[0])), end=int(te[-1]), **common)
    return train, test

for mode in ('compact', 'full'):
    tr, _ = make_envs(data, lookback=30, lam=0.5, feature_mode=mode)
    check_env(tr)
    print(f'{mode:8s} obs dim {tr.observation_space.shape[0]:5d} | action dim {tr.action_space.shape[0]}')

"""### Baselines and metrics

"""

def max_sharpe(mu, cov):
    N = len(mu)
    neg = lambda w: -(w @ mu) / (np.sqrt(w @ cov @ w) + 1e-12)
    cons = ({'type': 'eq', 'fun': lambda w: w.sum() - 1},)
    r = minimize(neg, np.ones(N) / N, method='SLSQP', bounds=[(0, 1)] * N,
                 constraints=cons, options={'maxiter': 500, 'ftol': 1e-9})
    w = np.clip(r.x, 0, None)
    return w / w.sum()

def equal_weight(simple, s, e, tc=0.001):
    N = simple.shape[1]; tgt = np.ones(N) / N; w = np.zeros(N); out = []
    for t in range(s, e):
        cost = tc * np.abs(tgt - w).sum(); w = tgt.copy()
        out.append(float(w @ simple[t + 1]) - cost)
        g = w * (1 + simple[t + 1]); w = g / g.sum()
    return np.array(out)

def markowitz(simple, s, e, window=252, rebal=21, tc=0.001):
    N = simple.shape[1]; w = np.zeros(N); out = []
    for t in range(s, e):
        if (t - s) % rebal == 0:
            past = simple[max(0, t - window):t]
            tgt = max_sharpe(past.mean(0) * 252, np.cov(past.T) * 252)
            cost = tc * np.abs(tgt - w).sum(); w = tgt
        else:
            cost = 0.0
        out.append(float(w @ simple[t + 1]) - cost)
        g = w * (1 + simple[t + 1]); w = g / g.sum()
    return np.array(out)

def buy_and_hold(simple, s, e, idx):
    return simple[s + 1:e + 1, idx].astype(float).copy()

def backtest(model, env):
    obs, _ = env.reset(); done = False; rets, ws = [], []
    while not done:
        a, _ = model.predict(obs, deterministic=True)
        obs, _, term, trunc, info = env.step(a); done = term or trunc
        rets.append(info['ret'] - info['cost']); ws.append(info['weights'])
    return np.array(rets), np.array(ws)

def metrics(rets):
    rets = np.asarray(rets, float)
    cum = float(np.prod(1 + rets) - 1)
    yrs = len(rets) / 252
    cagr = (1 + cum) ** (1 / yrs) - 1 if (1 + cum) > 0 and yrs > 0 else np.nan
    vol = float(rets.std() * np.sqrt(252))
    sharpe = float(rets.mean() / (rets.std() + 1e-12) * np.sqrt(252))
    eq = np.cumprod(1 + rets); dd = float((eq / np.maximum.accumulate(eq) - 1).min())
    down = rets[rets < 0]
    sortino = float(rets.mean() / (down.std() + 1e-12) * np.sqrt(252)) if len(down) else np.nan
    calmar = float(cagr / abs(dd)) if (dd < 0 and not np.isnan(cagr)) else np.nan
    return {'Total Return': cum, 'CAGR': cagr, 'Volatility': vol, 'Sharpe': sharpe,
            'Sortino': sortino, 'Max Drawdown': dd, 'Calmar': calmar}

"""Quick sanity check before the long grid — train PPO briefly and confirm the loop fits together. 20k steps isn't meant to be good."""

tr, te = make_envs(data, lookback=30, lam=0.5, feature_mode=FEATURE_MODE)
demo = PPO('MlpPolicy', Monitor(tr), seed=0, verbose=0, device='cpu')
demo.learn(20_000)
r, _ = backtest(demo, te)
ti = np.where(data['test_mask'])[0]; s, e = int(ti[0]), int(ti[-1])
ew = equal_weight(data['simple_ret'], s, e)
print('demo PPO Sharpe', round(metrics(r)['Sharpe'], 2),
      '| 1/N Sharpe', round(metrics(ew)['Sharpe'], 2))
plt.figure(figsize=(11, 4))
plt.plot(np.cumprod(1 + r), label='PPO (demo)')
plt.plot(np.cumprod(1 + ew), label='1/N')
plt.legend(); plt.title('Sanity check — test equity'); plt.grid(alpha=.3); plt.show()

"""### Experiments

"""

ALGOS = ['PPO', 'A2C', 'SAC', 'TD3']
LAMBDAS = [0.0, 0.5, 1.0]
LOOKBACKS = [30, 60]
SEEDS = [0, 1, 2]
STEPS = 50_000
EXTRA = {'PPO': {}, 'A2C': {},
         'SAC': {'buffer_size': 50_000, 'learning_starts': 1000},
         'TD3': {'buffer_size': 50_000, 'learning_starts': 1000}}
print('grid size:', len(ALGOS) * len(LAMBDAS) * len(LOOKBACKS) * len(SEEDS), 'runs')

results = pd.read_csv(RES_CSV) if os.path.exists(RES_CSV) else pd.DataFrame()
done = set(results['run_id']) if len(results) else set()
total = len(ALGOS) * len(LAMBDAS) * len(LOOKBACKS) * len(SEEDS); i = 0
for name in ALGOS:
    for lam in LAMBDAS:
        for lb in LOOKBACKS:
            for sd in SEEDS:
                i += 1
                run = f'{name}_l{lam}_lb{lb}_s{sd}'
                if run in done:
                    print(f'[{i:2d}/{total}] skip {run}'); continue

                t0 = time.time()
                train_env, test_env = make_envs(data, lb, lam, FEATURE_MODE)
                train_env = Monitor(train_env, os.path.join(LOG_DIR, run))
                model = ALGO_MAP[name]('MlpPolicy', train_env, seed=sd, verbose=0,
                                       device='cpu', tensorboard_log=TB_DIR, **EXTRA[name])
                model.learn(STEPS, tb_log_name=run)
                model.save(os.path.join(MODEL_DIR, run))

                rets, _ = backtest(model, test_env)
                np.save(os.path.join(RES_DIR, run + '.npy'), rets)
                m = metrics(rets)
                row = {'run_id': run, 'algo': name, 'lambda': lam, 'lookback': lb,
                       'seed': sd, **m, 'min': (time.time() - t0) / 60}
                results = pd.concat([results, pd.DataFrame([row])], ignore_index=True)
                results.to_csv(RES_CSV, index=False)
                print(f"[{i:2d}/{total}] {run:20s} Sharpe {m['Sharpe']:5.2f}  ({row['min']:.1f}m)")

results = pd.read_csv(RES_CSV)
print(len(results), 'runs across', results['algo'].nunique(), 'algorithms,',
      results['seed'].nunique(), 'seeds')
results.sort_values('Sharpe', ascending=False).head(10).round(3).reset_index(drop=True)

"""Watch training in TensorBoard if you like:"""

# Commented out IPython magic to ensure Python compatibility.
# %load_ext tensorboard
# %tensorboard --logdir $TB_DIR

"""### Results and comparison

"""

ti = np.where(data['test_mask'])[0]; s, e = int(ti[0]), int(ti[-1])
ew = equal_weight(data['simple_ret'], s, e)
mv = markowitz(data['simple_ret'], s, e)
np.save(os.path.join(RES_DIR, 'equal_weight.npy'), ew)
np.save(os.path.join(RES_DIR, 'markowitz.npy'), mv)
base = {'Equal-weight (1/N)': metrics(ew), 'Markowitz (max-Sharpe)': metrics(mv)}
agg = results.groupby(['algo', 'lambda', 'lookback']).agg(
    Sharpe_mean=('Sharpe', 'mean'), Sharpe_std=('Sharpe', 'std'),
    Return_mean=('Total Return', 'mean'), CAGR_mean=('CAGR', 'mean'),
    Vol_mean=('Volatility', 'mean'), MDD_mean=('Max Drawdown', 'mean'),
    Calmar_mean=('Calmar', 'mean')).reset_index()
agg_sorted = agg.sort_values('Sharpe_mean', ascending=False).reset_index(drop=True)
agg_sorted.to_csv(os.path.join(RES_DIR, 'agg_by_config.csv'), index=False)
print('Baselines:'); display(pd.DataFrame(base).T.round(4))
print('Agents (mean over seeds), top configs:'); agg_sorted.round(3)

"""**Sharpe by algorithm.** For each algorithm we take its best configuration (by mean Sharpe over seeds); the error bar is the std **across the 3 seeds** of that configuration — i.e. genuine run-to-run noise."""

best_cfg = agg.loc[agg.groupby('algo')['Sharpe_mean'].idxmax()].set_index('algo')
order = best_cfg['Sharpe_mean'].sort_values(ascending=False).index
plt.figure(figsize=(10, 5))
plt.bar(order, best_cfg.loc[order, 'Sharpe_mean'],
        yerr=best_cfg.loc[order, 'Sharpe_std'].fillna(0), capsize=6, alpha=.85,
        label='best config per algorithm (mean ± std over seeds)')
for label, fn, ls in [('1/N', 'equal_weight', '--'), ('Markowitz', 'markowitz', ':')]:
    plt.axhline(metrics(np.load(os.path.join(RES_DIR, fn + '.npy')))['Sharpe'],
                color='k', ls=ls, label=label)
plt.ylabel('Sharpe'); plt.title('Test Sharpe by algorithm vs baselines')
plt.legend(); plt.grid(axis='y', alpha=.3); plt.tight_layout(); plt.show()

"""**Risk aversion vs lookback.** Mean test Sharpe (over seeds) for each $\lambda$ and lookback, one heatmap per algorithm."""

algos = list(agg['algo'].unique())
fig, ax = plt.subplots(1, len(algos), figsize=(4 * len(algos), 3.6))
if len(algos) == 1:
    ax = [ax]
vmin, vmax = agg['Sharpe_mean'].min(), agg['Sharpe_mean'].max()
for axi, a in zip(ax, algos):
    piv = agg[agg.algo == a].pivot(index='lambda', columns='lookback', values='Sharpe_mean')
    im = axi.imshow(piv.values, cmap='viridis', vmin=vmin, vmax=vmax, aspect='auto')
    axi.set_xticks(range(len(piv.columns))); axi.set_xticklabels(piv.columns)
    axi.set_yticks(range(len(piv.index))); axi.set_yticklabels(piv.index)
    axi.set_title(a); axi.set_xlabel('lookback'); axi.set_ylabel('λ')
    for r_ in range(piv.shape[0]):
        for c_ in range(piv.shape[1]):
            axi.text(c_, r_, f'{piv.values[r_, c_]:.2f}', ha='center', va='center', color='w')
fig.colorbar(im, ax=ax, fraction=0.025, label='mean Sharpe')
plt.show()

"""**Out-of-sample equity**, best configuration per algorithm (averaged over its seeds) against the baselines."""

test_dates = data['dates'][s + 1: e + 1]
def config_runs(a, lam, lb):
    m = (results.algo == a) & (results['lambda'] == lam) & (results.lookback == lb)
    return results[m]['run_id'].tolist()
plt.figure(figsize=(13, 6))
for a in agg['algo'].unique():
    row = agg[agg.algo == a].sort_values('Sharpe_mean').iloc[-1]
    mat = np.vstack([np.load(os.path.join(RES_DIR, r + '.npy'))
                     for r in config_runs(a, row['lambda'], row['lookback'])])
    eq = np.cumprod(1 + mat.mean(0))
    plt.plot(test_dates[:len(eq)], eq, label=f"{a} (λ={row['lambda']}, L={int(row['lookback'])})")
for label, fn, ls in [('1/N', 'equal_weight', '--'), ('Markowitz', 'markowitz', ':')]:
    r = np.load(os.path.join(RES_DIR, fn + '.npy'))
    plt.plot(test_dates[:len(r)], np.cumprod(1 + r), 'k', ls=ls, label=label)
plt.ylabel('growth of $1'); plt.title('Out-of-sample equity (best config per algorithm)')
plt.legend(); plt.grid(alpha=.3); plt.tight_layout(); plt.show()

"""**What is the best agent actually doing?** Its allocation over time (including the cash sleeve) and its drawdown. This is where the active cash position shows up."""

best = agg.sort_values('Sharpe_mean').iloc[-1]
cfg = results[(results.algo == best.algo) & (results['lambda'] == best['lambda']) &
              (results.lookback == best.lookback)].sort_values('Sharpe')
pick = cfg.iloc[len(cfg) // 2]['run_id']
model = ALGO_MAP[best.algo].load(os.path.join(MODEL_DIR, pick))
_, te = make_envs(data, int(best.lookback), best['lambda'], FEATURE_MODE)
rets, ws = backtest(model, te)
fig, ax = plt.subplots(2, 1, figsize=(13, 8), sharex=True)
ax[0].stackplot(test_dates[:len(ws)], ws.T, labels=data['tickers'] + ['CASH'])
ax[0].set_title(f'Portfolio weights over time — {pick}'); ax[0].set_ylabel('weight')
ax[0].legend(loc='upper left', ncol=4, fontsize=8); ax[0].margins(x=0)
eq = np.cumprod(1 + rets); dd = eq / np.maximum.accumulate(eq) - 1
ax[1].fill_between(test_dates[:len(dd)], dd * 100, 0, color='crimson', alpha=.4)
ax[1].set_title('Drawdown'); ax[1].set_ylabel('drawdown %'); ax[1].grid(alpha=.3)
plt.tight_layout(); plt.show()

"""**Training curves** (episode reward, smoothed) for the median-seed run of each algorithm's best configuration."""

plt.figure(figsize=(11, 5))
for a in agg['algo'].unique():
    row = agg[agg.algo == a].sort_values('Sharpe_mean').iloc[-1]
    runs = config_runs(a, row['lambda'], row['lookback'])
    sub = results[results['run_id'].isin(runs)].sort_values('Sharpe')
    pick = sub.iloc[len(sub) // 2]['run_id']
    path = os.path.join(LOG_DIR, pick + '.monitor.csv')
    if not os.path.exists(path):
        continue
    mon = pd.read_csv(path, skiprows=1)
    plt.plot(mon['l'].cumsum(), mon['r'].rolling(5, min_periods=1).mean(), label=f'{a} ({pick})')
plt.xlabel('timesteps'); plt.ylabel('episode reward (rolling mean)')
plt.title('Training curves (best config per algorithm)')
plt.legend(); plt.grid(alpha=.3); plt.tight_layout(); plt.show()

"""## Investment simulation: \$10,000 over one year

"""

CAP = 10_000
YEAR = min(252, e - s)
best = agg.sort_values('Sharpe_mean').iloc[-1]
best_runs = config_runs(best.algo, best['lambda'], best.lookback)
model_mat = np.vstack([np.load(os.path.join(RES_DIR, r + '.npy'))[:YEAR] for r in best_runs])
model_eq = CAP * np.cumprod(1 + model_mat, axis=1)
model_mean_ret = model_mat.mean(0)
paths = {
    f'RL model ({best.algo})': model_mean_ret,
    'Equal-weight (1/N)': equal_weight(data['simple_ret'], s, e)[:YEAR],
    'Markowitz (max-Sharpe)': markowitz(data['simple_ret'], s, e)[:YEAR],
    'Buy & hold SPY': buy_and_hold(data['simple_ret'], s, e, data['tickers'].index('SPY'))[:YEAR],
}
summary = []
for k, rr in paths.items():
    val = CAP * np.cumprod(1 + rr)
    m = metrics(rr)
    summary.append({'strategy': k, 'final $': round(val[-1], 2),
                    'profit $': round(val[-1] - CAP, 2), 'ROI %': round((val[-1] / CAP - 1) * 100, 2),
                    'volatility %': round(m['Volatility'] * 100, 2),
                    'max DD %': round(m['Max Drawdown'] * 100, 2), 'Sharpe': round(m['Sharpe'], 2)})
summary = pd.DataFrame(summary).sort_values('final $', ascending=False).reset_index(drop=True)
summary.to_csv(os.path.join(RES_DIR, 'investment_10k_1y.csv'), index=False)
summary

days = test_dates[:YEAR]
fig, ax = plt.subplots(1, 2, figsize=(15, 5.5))
ax[0].fill_between(days, model_eq.min(0), model_eq.max(0), alpha=.2, label='RL seeds range')
for k, rr in paths.items():
    ax[0].plot(days, CAP * np.cumprod(1 + rr), label=k, lw=2 if k.startswith('RL') else 1.3)
ax[0].axhline(CAP, color='gray', ls=':')
ax[0].set_title('Value of a $10,000 investment over one year'); ax[0].set_ylabel('portfolio value ($)')
ax[0].legend(fontsize=8); ax[0].grid(alpha=.3)
for k, rr in paths.items():
    ax[1].plot(days, (np.cumprod(1 + rr) - 1) * 100, label=k, lw=2 if k.startswith('RL') else 1.3)
ax[1].axhline(0, color='gray', ls=':')
ax[1].set_title('Cumulative ROI (%)'); ax[1].set_ylabel('return %'); ax[1].legend(fontsize=8); ax[1].grid(alpha=.3)
plt.tight_layout(); plt.show()

top = summary.iloc[0]
mdl = summary[summary.strategy.str.startswith('RL')].iloc[0]
print(f'Starting capital: ${CAP:,.0f}   |   horizon: {YEAR} trading days (~1 year)\n')
print('Final value (ranked):')
for _, r in summary.iterrows():
    print(f"  {r['strategy']:24s} ${r['final $']:>11,.0f}   ROI {r['ROI %']:+6.2f}%   "
          f"maxDD {r['max DD %']:6.2f}%   Sharpe {r['Sharpe']:.2f}")
print()
print(f"- Highest ending value: {top['strategy']} at ${top['final $']:,.0f} "
      f"({top['ROI %']:+.2f}%).")
print(f"- The RL model finished at ${mdl['final $']:,.0f} ({mdl['ROI %']:+.2f}%), "
      f"a {'profit' if mdl['profit $'] >= 0 else 'loss'} of ${abs(mdl['profit $']):,.0f}.")
print(f"- Risk: the RL model's worst drawdown was {mdl['max DD %']:.2f}% at "
      f"{mdl['volatility %']:.2f}% annual volatility, Sharpe {mdl['Sharpe']:.2f}.")
best_risk = summary.sort_values('Sharpe', ascending=False).iloc[0]
print(f"- Best risk-adjusted (Sharpe): {best_risk['strategy']} at {best_risk['Sharpe']:.2f}.")

"""### Reading the result

Use the table and the printout above to write the discussion. The questions that matter:

- **Absolute vs risk-adjusted.** Did the RL model make the most *money*, or the most money
  *per unit of risk*? They are not always the same strategy — a higher Sharpe with a smaller
  drawdown can be the better outcome even if the ending dollar value is lower.
- **What did the model do to get there?** Look back at the weights-over-time chart: did it
  concentrate, rotate between assets, or sit in cash during the rough patches? Tie the drawdown
  chart to the allocation.
- **Costs and turnover.** The 0.1% cost penalizes churn; a strategy that rebalances constantly
  pays for it. Mention whether the model learned to keep turnover down.
- **Honesty about scope.** This is one test window after a single train/test split, and past
  performance is not a guarantee — say so. The seed band shows how much the outcome moves just
  from the random seed, which is itself a useful caveat.

"""